### ISSUE TITLE
Unable to parse % traceroute -n;

### ISSUE THREAD

**Issue by zstyblik** [lbenitez000/trparse#5]
Hello,

it seems that parsing of % traceroute -n; output isn't supported which is a pity :/

```
Traceback (most recent call last):
  File "traceroute.py", line 28, in <module>
    main()
  File "traceroute.py", line 24, in main
    traceroute = trparse.loads(out)
  File "venv/local/lib/python2.7/site-packages/trparse.py", line 135, in loads
    rtt = float(probes_data[i+2])
ValueError: invalid literal for float(): 108.170.245.49
```

**Comment by zstyblik** [comment]
A-ha, problem is in traceroute's output:

```
 8  72.14.220.74  3.792 ms  2.809 ms  3.774 ms
 9  108.170.245.33  4.922 ms 108.170.245.49  4.940 ms 108.170.245.33  9.219 ms
10  108.170.235.147  8.034 ms 108.170.235.149  7.223 ms  6.694 ms
11  8.8.8.8  7.846 ms  6.408 ms  6.928 ms
```

**Comment by zstyblik** [comment]
I know it's a dirty fix, but it works:

```
            elif RE_PROBE_NAME.match(probes_data[i]):
                # Matched a name, so next elements are IP and rtt
                name = probes_data[i]
                ip = probes_data[i+1].strip('()')
                j = i + 1
                while j < len(probes_data):
                    if len(probes_data[j].split('.')) != 2:
                        probes_data.pop(j)
                    else:
                        j += 1

                rtt = float(probes_data[i+2])
                i += 3
```

... although, it breaks annotations and RTT ends up in the place of annotation. Back to zero.

**Comment by rarylson** [comment]
Same problem here.

The library supposes that the output is in format `HOP NAME (IP) PROBES`:

```
 1  192.168.0.1 (192.168.0.1)  1.349 ms
 2  3-161-45-187.static.in-addr.vialink.com.br (187.45.161.3)  4.803 ms
 3  192.168.149.1 (192.168.149.1)  6.985 ms
 4  49-170-45-187.static.in-addr.vialink.com.br (187.45.170.49)  6.404 ms
 5  65-161-45-187.static.in-addr.vialink.com.br (187.45.161.65)  9.264 ms
```

Only IP output (`HOP IP PROBES`) is not currently supported:

```
 1  192.168.0.1  3.860 ms
 2  187.45.161.3  2.863 ms
 3  192.168.149.1  9.664 ms
 4  187.45.170.49  8.769 ms
 5  187.45.161.65  10.631 ms
```

I don't know if this is a simple fix (the traceroute output can have `!` annotations and it complicates things). I'll try to fix it and, if I can do this, propose a patch to the project owner.

**Comment by rarylson** [comment]
I realized two things:

1. @lbenitez000 doesn't answer issues from this project since Dec 2, 2016. Last commit was from Jan, 2017. Is this project still maintained? @lbenitez000, I can help you if you need.
2. This project is very similar to https://github.com/ckreibich/tracerouteparser.py/
    - The last project doesn't exist in Pypi (to be installed with pip). This is way I'm using this one;
    - This project imports `cStringIO`, although its not used. The project from ckreibich also imports this module (and uses it). So, is this project based somehow in the ckreibich traceroute parser?

**Comment by rarylson** [comment]
The new version, v0.3.0, still doesn't support `traceroute -n` outputs.

**Comment by harendra247** [comment]
To make `traceroute -n` work please use the following

`RE_PROBE_NAME_IP = re.compile(r'(\S+)\s+(?:\((\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|([0-9a-fA-F:]+)\))*')`


`probe_ip = probe_name_ip_match.group(2) or probe_name_ip_match.group(3) or probe_name`
